### ISSUE TITLE
fails with GDAL 3.0.1 and PROJ 6.2.0

### ISSUE THREAD

**Issue by rsbivand** [ropensci/grainchanger#5]
[error.zip](https://github.com/ropensci/grainchanger/files/3685131/error.zip) are logs from running R CMD check with the current version of rgdal built against current GDAL and PROJ. I don't read testthat, so I'll let you find out what is going on.

**Comment by laurajanegraham** [comment]
Thanks for this. I'll look into this and sort the issue.

**Comment by laurajanegraham** [comment]
Apologies for the delayed response. This has now been fixed and the package resubmitted to CRAN (it was archived as this was a problem caused by the new version of linux rather than being specific to GDAL)
