### ISSUE TITLE
Please update repo URL

### ISSUE THREAD

**Issue by maelle** [ropensci/grainchanger#7]
To https://docs.ropensci.org/grainchanger/ 🙂

**Comment by laurajanegraham** [comment]
Do you mean in the description field on the top of the repo? If so, I'm not actually able to change that, and I'm not sure why.

**Comment by maelle** [comment]
Ah, good to know, we had forgotten to give you admin rights back! Now you should have all rights again.

**Comment by laurajanegraham** [comment]
Thanks - all sorted now :)
